import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: { params: { filename: string } }
) {
  try {
    const { searchParams } = new URL(request.url)
    const sourceCode = searchParams.get('code')
    const questionTitle = searchParams.get('title')

    if (!sourceCode) {
      return NextResponse.json({ error: 'Source code content is required' }, { status: 400 })
    }

    // Create the file content
    const fileContent = `// Source Code Generated by AI Assistant
// Question: ${questionTitle || 'Unknown'}
// Generated on: ${new Date().toISOString()}

${sourceCode}

// End of generated source code
`

    // Create response with appropriate headers for JavaScript file download
    const response = new NextResponse(fileContent, {
      status: 200,
      headers: {
        'Content-Type': 'application/javascript',
        'Content-Disposition': `attachment; filename="${params.filename}"`,
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET',
        'Access-Control-Allow-Headers': 'Content-Type',
      },
    })

    return response

  } catch (error) {
    console.error('Error serving source code:', error)
    return NextResponse.json({ error: 'Failed to serve source code' }, { status: 500 })
  }
}
